export default [{
  name: '文章',
  path: '/article/list?scope=1&status=all',
  icon: 'icon-article'
}, {
  name: '图集',
  path: '/gallery',
  icon: 'icon-gallery'
}, {
  name: '视频',
  path: '/videos',
  icon: 'icon-videos'
}, {
  name: '音频',
  path: '/audios',
  icon: 'icon-audios'
}, {
  name: '专题',
  path: '/topics',
  icon: ''
}, {
  name: '直播',
  path: '/live',
  icon: ''
}, {
  name: '链接',
  path: '/links',
  icon: ''
}, {
  name: '会员用户',
  path: '/members',
  icon: ''
}, {
  name: '素材库',
  path: '/media',
  icon: 'icon-media'
}, {
  name: '站点设置',
  path: '/webSettings',
  icon: ''
}, {
  name: '设置',
  path: '/settings',
  icon: 'icon-settings'
}]
