export default [{
  name: '文章',
  path: '/article/list?scope=all&status=all',
  icon: 'icon-article'
}, {
  name: '图集',
  path: '/gallery',
  icon: 'icon-gallery'
}, {
  name: '视频',
  path: '/videos',
  icon: 'icon-videos'
}, {
  name: '音频',
  path: '/audios',
  icon: 'icon-audios'
}, {
  name: '专题',
  path: '/topics',
  icon: 'icon-special'
}, {
  name: '直播',
  path: '/live',
  icon: 'icon-live'
}, {
  name: '链接',
  path: '/links',
  icon: 'icon-links'
}, {
  name: '工作台',
  path: '/works',
  icon: 'icon-todo'
}, {
  name: '素材库',
  path: '/media',
  icon: 'icon-media'
}, {
  name: '用户',
  path: '/users',
  icon: 'icon-users'
}, {
  name: '设置',
  path: '/settings',
  icon: 'icon-settings'
}]
